[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
regex = "1.11.1"

[dev-dependencies]
divan = { version = "0.1.16" }


[[bench]]
name = "benchmarks"
path = "benchmarks/benchmarks.rs"
harness = false
